import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { buildI18NServerSideProps } from '@i18next-toolkit/react-nextjs/lib/server';
import styles from '@/styles/Home.module.css';
import { Trans, useTranslation } from '@i18next-toolkit/react-nextjs';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>{t('Create Next App')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Trans>
            <p>
              Get started by editing&nbsp;
              <code className={styles.code}>src/pages/index.tsx</code>
            </p>
          </Trans>
          <div>
            <button onClick={() => i18n.changeLanguage('en')}>en</button>
            <button onClick={() => i18n.changeLanguage('fr')}>fr</button>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              {t('Find in-depth information about Next.js features and API.')}
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              {t('Learn about Next.js in an interactive course with quizzes!')}
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              {t('Discover and deploy boilerplate example Next.js projects.')}
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              {t(
                'Instantly deploy your Next.js site to a shareable URL with Vercel.'
              )}
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

export const getStaticProps = buildI18NServerSideProps();
