import { OpenAI } from 'openai';
import { config } from '../config';
import _chunk from 'lodash/chunk';
import { ProxyAgent } from 'proxy-agent';

export async function generateTranslationFromOpenai(
  untranslated: Record<string, Record<string, string>>
) {
  const res: Record<string, string> = {};

  for (const locale in untranslated) {
    const json = untranslated[locale];

    if (Object.keys(json).length === 0) {
      console.log(`[${locale}] has no word need to translate, skip.`);
      continue;
    }

    console.log('Is translating:', locale);

    const { translation, usage } = await translateWithOpenAI(locale, json);

    res[locale] = JSON.stringify(translation);

    console.log('DONE, usage tokens:', usage);
  }

  return res;
}

export async function translateWithOpenAI(
  locale: string,
  originTranslation: Record<string, string>
) {
  const {
    baseURL = process.env.OPENAPI_HOST,
    apiKey = process.env.OPENAPI_KEY,
    modelName = 'gpt-4o-mini',
  } = config.translator?.openai ?? {};

  if (!apiKey) {
    throw new Error(
      'need openai config with `translator.openai` or environment `OPENAPI_KEY`'
    );
  }

  const openai = new OpenAI({
    apiKey: apiKey,
    baseURL,
    httpAgent: new ProxyAgent(),
  });

  let translation = {};
  let usage = 0;
  for (const item of _chunk(Object.entries(originTranslation), 80)) {
    const json = JSON.stringify(Object.fromEntries(item), null, 2);

    const chatCompletion = await openai.chat.completions.create({
      model: modelName,
      messages: [
        {
          role: 'system',
          content: `
You are a professional translation tool specialized in handling JSON data within a software development context.
The input is a flat JSON object where each key is a hash value generated by a computer program (e.g., MD5, SHA-256). These keys should remain unchanged.
Your task is to translate the textual content of each value into '${locale}' (please specify the target language as needed), while ensuring that common computer terms (such as API, JSON, module, system, etc.) are preserved in their original form.

Requirements:
1. Do not translate or modify the keys.
2. Only translate the textual content of the values.
3. Ensure that any computer-related or technical terminology remains unaltered.
4. Maintain the flat JSON structure; the output must be valid JSON.
`.trim(),
        },
        {
          role: 'user',
          content: json,
        },
      ],
      stream: false,
      temperature: 0,
      response_format: {
        type: 'json_object',
      },
    });

    translation = {
      ...translation,
      ...JSON.parse(chatCompletion.choices[0].message.content ?? '{}'),
    };
    usage += chatCompletion.usage?.total_tokens ?? 0;
  }

  return { translation, usage };
}
